/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewer;

import controler.Actividade;
import controler.Categoria;
import controler.Distrito;
import controler.Empresa;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import controler.PathFile;
import controler.Provincia;
import controler.Sindicato;
import controler.TipoRegisto;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;

/**
 *
 * @author User
 */
public class FrmCadSindicato extends javax.swing.JDialog {

    /* Array para receber os dados do ficheiro de texto e manuseamento de dados
       no programa java */
    private Sindicato sindicatos[] = new Sindicato[100];
    private int nrElem = 0;
    
    public FrmCadSindicato(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadTipoRegistos();
        loadActividades();        
        loadProvincias();
        loadSindicatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfcActa = new javax.swing.JFileChooser();
        jfcEstatuto = new javax.swing.JFileChooser();
        jfcLista = new javax.swing.JFileChooser();
        jfcCertidao = new javax.swing.JFileChooser();
        jfcConvocatoria = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbTipoReg = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbCatReg = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtInss = new javax.swing.JTextField();
        btBuscaEmp = new javax.swing.JButton();
        txtNomeEmp = new javax.swing.JTextField();
        btAddEmp = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbActiv = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtSigla = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesigna = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbProv = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbDist = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEndereco = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        txtData = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        txtContacto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtRepresenta = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtActaFile = new javax.swing.JTextField();
        txtEstatutoFile = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtListaFile = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtFileCertidao = new javax.swing.JTextField();
        btBuscaActa = new javax.swing.JButton();
        btBuscaEstatuto = new javax.swing.JButton();
        btBuscaLista = new javax.swing.JButton();
        btBuscaOutros = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtFileConvocatoria = new javax.swing.JTextField();
        btBuscaOutros1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btGravar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTO DO SINDICATO/ASSOCIAÇÃO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("TIPO DO REGISTO *");

        cbTipoReg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------------------ SELECCIONA O TIPO DO REGISTO --------------------" }));
        cbTipoReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoRegActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("CATEGORIA DO REGISTO *");

        cbCatReg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------------- SELECCIONA A CATEGORIA DO REGISTO ---------------" }));
        cbCatReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCatRegActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("NUM INSS DA EMPRESA  ");

        txtInss.setEnabled(false);

        btBuscaEmp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btBuscaEmp.setForeground(new java.awt.Color(51, 0, 255));
        btBuscaEmp.setText("BUSCAR");
        btBuscaEmp.setEnabled(false);
        btBuscaEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscaEmpActionPerformed(evt);
            }
        });

        txtNomeEmp.setEditable(false);
        txtNomeEmp.setAutoscrolls(false);
        txtNomeEmp.setEnabled(false);

        btAddEmp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btAddEmp.setForeground(new java.awt.Color(255, 0, 51));
        btAddEmp.setText("ADD");
        btAddEmp.setEnabled(false);
        btAddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddEmpActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("SECTOR DE ACTIVIDADE ");

        cbActiv.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        cbActiv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------------- SELECCIONA O SECTOR DE ACTIVIDADE ---------------" }));
        cbActiv.setEnabled(false);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("SIGLA *");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("DESIGNACAO *");

        txtDesigna.setColumns(20);
        txtDesigna.setLineWrap(true);
        txtDesigna.setRows(2);
        jScrollPane1.setViewportView(txtDesigna);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtSigla, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtInss, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBuscaEmp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAddEmp))
                    .addComponent(jScrollPane1)
                    .addComponent(cbTipoReg, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbCatReg, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbActiv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipoReg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCatReg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInss, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscaEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(txtNomeEmp)
                    .addComponent(btAddEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbActiv, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("PROVINCIA *");

        cbProv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------------- SELECCIONA PROVINCIA ---------------" }));
        cbProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProvActionPerformed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("DISTRITO *");

        cbDist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------------- SELECCIONA DISTRITO ---------------" }));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("ENDEREÇO *");

        txtEndereco.setColumns(20);
        txtEndereco.setLineWrap(true);
        txtEndereco.setRows(2);
        jScrollPane2.setViewportView(txtEndereco);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("DATA INSCRIÇÃO  *");

        txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("YYYY-MM-dd"))));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("CONTACTO *");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("REPRESENTANTE *");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRepresenta, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbProv, 0, 330, Short.MAX_VALUE)
                    .addComponent(cbDist, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbProv, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDist, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(txtData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRepresenta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("FICHEIRO DA ACTA DA REUNIAO *");

        txtActaFile.setEditable(false);

        txtEstatutoFile.setEditable(false);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("FICHEIRO DE ESTATUTO *");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("FICHEIRO DE LISTA DE PRESENÇAS *");

        txtListaFile.setEditable(false);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("FICHEIRO DA CERTIDÃO DA DENOMINA'ÇÃO *");

        txtFileCertidao.setEditable(false);

        btBuscaActa.setText("BUSCAR FICHEIRO");
        btBuscaActa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscaActaActionPerformed(evt);
            }
        });

        btBuscaEstatuto.setText("BUSCAR FICHEIRO");
        btBuscaEstatuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscaEstatutoActionPerformed(evt);
            }
        });

        btBuscaLista.setText("BUSCAR FICHEIRO");
        btBuscaLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscaListaActionPerformed(evt);
            }
        });

        btBuscaOutros.setText("BUSCAR FICHEIRO");
        btBuscaOutros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscaOutrosActionPerformed(evt);
            }
        });

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("FICHEIRO DA PUBLICAÇÃO CONVOCATORIA*");

        txtFileConvocatoria.setEditable(false);

        btBuscaOutros1.setText("BUSCAR FICHEIRO");
        btBuscaOutros1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscaOutros1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEstatutoFile)
                            .addComponent(txtActaFile))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btBuscaActa))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btBuscaEstatuto))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFileCertidao)
                            .addComponent(txtListaFile)
                            .addComponent(txtFileConvocatoria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btBuscaOutros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btBuscaLista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btBuscaOutros1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(19, 19, 19))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtActaFile, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscaActa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtEstatutoFile, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscaEstatuto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtListaFile, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscaLista, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtFileCertidao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscaOutros, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtFileConvocatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscaOutros1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OPERAÇÕES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        btGravar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btGravar.setText("GRAVAR");
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(btGravar)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(btGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscaActaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscaActaActionPerformed
        int valPath = jfcActa.showOpenDialog(this);
        if(valPath == JFileChooser.APPROVE_OPTION){
            File ficheiro = jfcActa.getSelectedFile();
            txtActaFile.setText(ficheiro.getPath());
        }
    }//GEN-LAST:event_btBuscaActaActionPerformed

    private void cbCatRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCatRegActionPerformed
        String category="--------------- SELECCIONA A CATEGORIA DO REGISTO ---------------";
        txtInss.setText(null);
        txtNomeEmp.setText(null);
        cbActiv.setSelectedIndex(0);
        // Habilitar ou Desabilitar as edições dos campos em função de ser sindicado/associação da empresa ou do sector
        if(cbCatReg.getSelectedIndex() > 0){
            category=cbCatReg.getSelectedItem().toString().split(" - ")[1];
            if(category.equalsIgnoreCase("Sindicato Corporativo") || category.equalsIgnoreCase("Associacao Corporativo") ){
                txtInss.setEnabled(true);
                btBuscaEmp.setEnabled(true);
                txtNomeEmp.setEnabled(true);
                btAddEmp.setEnabled(true);
                cbActiv.setEnabled(false);
            }else{
                txtInss.setEnabled(false);
                btBuscaEmp.setEnabled(false);
                txtNomeEmp.setEnabled(false);
                btAddEmp.setEnabled(false);
                cbActiv.setEnabled(true); 
            }
        }else{
            txtInss.setEnabled(false);
            btBuscaEmp.setEnabled(false);
            txtNomeEmp.setEnabled(false);
            btAddEmp.setEnabled(false);
            cbActiv.setEnabled(false); 
        }
    }//GEN-LAST:event_cbCatRegActionPerformed

    private void btBuscaEstatutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscaEstatutoActionPerformed
        int valPath = jfcEstatuto.showOpenDialog(this);
        if(valPath == JFileChooser.APPROVE_OPTION){
            File ficheiro = jfcEstatuto.getSelectedFile();
            txtEstatutoFile.setText(ficheiro.getPath());
        }
    }//GEN-LAST:event_btBuscaEstatutoActionPerformed

    private void btBuscaListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscaListaActionPerformed
        int valPath = jfcLista.showOpenDialog(this);
        if(valPath == JFileChooser.APPROVE_OPTION){
            File ficheiro = jfcLista.getSelectedFile();
            txtListaFile.setText(ficheiro.getPath());
        }
    }//GEN-LAST:event_btBuscaListaActionPerformed

    private void btBuscaOutrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscaOutrosActionPerformed
        int valPath = jfcCertidao.showOpenDialog(this);
        if(valPath == JFileChooser.APPROVE_OPTION){
            File ficheiro = jfcCertidao.getSelectedFile();
            txtFileCertidao.setText(ficheiro.getPath());
        }
    }//GEN-LAST:event_btBuscaOutrosActionPerformed

    private void cbProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProvActionPerformed
        cbDist.removeAllItems();
        cbDist.addItem("--------------- SELECCIONA DISTRITO ---------------");
        if(cbProv.getSelectedIndex() > 0){
            int codigo = Integer.parseInt(cbProv.getSelectedItem().toString().split(" - ")[0]);
            loadDistritos(codigo);
        }
    }//GEN-LAST:event_cbProvActionPerformed

    private void cbTipoRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoRegActionPerformed
        cbCatReg.removeAllItems();
        cbCatReg.addItem("--------------- SELECCIONA A CATEGORIA DO REGISTO ---------------");
        if(cbTipoReg.getSelectedIndex() > 0){
            int codigo = Integer.parseInt(cbTipoReg.getSelectedItem().toString().split(" - ")[0]);
            System.out.println(codigo);
            loadCategorias(codigo);
        }
    }//GEN-LAST:event_cbTipoRegActionPerformed

    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
        int codigo = nrElem+1;
        String sigla = txtSigla.getText();
        String desig = txtDesigna.getText();
        String repre = txtRepresenta.getText();
        int codDist  = Integer.parseInt(cbDist.getSelectedItem().toString().split(" - ")[0]);
        String ender = txtEndereco.getText();
        String conta = txtContacto.getText();
        Date dataIns = Date.valueOf(txtData.getText());
        int catego   = Integer.parseInt(cbCatReg.getSelectedItem().toString().split(" - ")[0]);
        int estado = 1;
        int numInss = 0;
        if(!txtNomeEmp.getText().isBlank()){
            numInss = Integer.parseInt(txtInss.getText());
        }
        int codActiv = 0;
        if(cbActiv.getSelectedIndex() > 0){
            codActiv = Integer.parseInt(cbActiv.getSelectedItem().toString().split(" - ")[0]);
        }
        String fileActa = new PathFile(txtActaFile.getText(), sigla+"_Acta_Deliberacao.pdf").getPath();
        String fileEstatuto = new PathFile(txtEstatutoFile.getText(), sigla+"_Estatuto_Aprovado.pdf").getPath();
        String fileLista = new PathFile(txtListaFile.getText(), sigla+"_Lista_Presencas.pdf").getPath();
        String fileCertid = new PathFile(txtFileCertidao.getText(), sigla+"_Certidao_da_Denominacao.pdf").getPath();
        String fileConvoca = new PathFile(txtFileConvocatoria.getText(), sigla+"_Convocatoria_Publicada.pdf").getPath();
        Date dataDesp = null;
        String despacho = null;
        Sindicato novoSind = new Sindicato(codigo, sigla, desig, repre, codDist, ender, conta, dataIns, catego, estado, numInss, codActiv, fileActa, fileEstatuto, fileLista, fileCertid, fileConvoca, dataDesp, despacho);
        if(search(codigo) == -1){
           addSindicato(novoSind) ;
        }else{
            JOptionPane.showMessageDialog(null, "Já existe empresa com este Número do INSS", "registo da empresa", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_btGravarActionPerformed

    private void btBuscaEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscaEmpActionPerformed
        if(!txtInss.getText().isBlank()){
            int inss = Integer.parseInt(txtInss.getText());
            Empresa emp = new Empresa().findEmpresa(inss);
            if(emp.getNumInss() == inss){
                if(emp.getEstado() == 2){
                    txtNomeEmp.setText(emp.getNome());
                }else{
                   JOptionPane.showMessageDialog(null, "Não pode criar o Sindicato/Associacao da empresa não aprovada", "registo do Sindicato", JOptionPane.ERROR_MESSAGE);   
                }                
            }else{
               JOptionPane.showMessageDialog(null, "Empresa não registada, registar a empresa atraves do botão ADD", "registo do Sindicato", JOptionPane.ERROR_MESSAGE);  
            }
            
        }
    }//GEN-LAST:event_btBuscaEmpActionPerformed

    private void btBuscaOutros1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscaOutros1ActionPerformed
        int valPath = jfcConvocatoria.showOpenDialog(this);
        if(valPath == JFileChooser.APPROVE_OPTION){
            File ficheiro = jfcConvocatoria.getSelectedFile();
            txtFileConvocatoria.setText(ficheiro.getPath());
        }
    }//GEN-LAST:event_btBuscaOutros1ActionPerformed

    private void btAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddEmpActionPerformed
        FrmCadEmpresa view = new FrmCadEmpresa(null, true);
        view.setLocationRelativeTo(null);
        view.setVisible(true);
    }//GEN-LAST:event_btAddEmpActionPerformed

    
    private void incrementaArry(){
        //verifica se o array está cheio, caso sim duplica a capacidade
        if(nrElem >= sindicatos.length){
            Sindicato aux[]= sindicatos;
            sindicatos = new Sindicato[aux.length * 2];
            for(int i = 0; i<aux.length; i++){
                sindicatos[i] = aux[i];
            }
        }
    }

    /* procura se existe um Sindicato com codigo igual ao valor no parametro 
       Existendo retorna a posição em foi inserida a tal Sindicato
    */
    private int search(int codigo){
    	int index=-1;
    	for(int i=0; i<nrElem; i++){
            if(sindicatos[i].getCodigo() == codigo){
                index=i;
                break;
            }
    	}    
    	return index;
    }
    
    // metodo que insere uma empresa no array de objecto Empresa
    public  void addSindicato(Sindicato novoSindicato){
        incrementaArry();
        // insere mais um Sindicato no array
        sindicatos[nrElem] = novoSindicato; 
        nrElem++;  
        // actualiza o ficheiro dos sindicatos
        updateTextFile();
    }
    
    // Grava todos as empresas do array no ficheiro de texto
    private void updateTextFile(){
    	try{
            FileWriter fileText = new FileWriter(new File("C:\\MyFiles\\GestaoSindicato\\SINDICATO.txt"));
            BufferedWriter writeText = new BufferedWriter(fileText);
            for(int i=0; i< nrElem ; i++){
                writeText.write(sindicatos[i].toString());
                writeText.newLine();
            }
            writeText.close();
            JOptionPane.showMessageDialog(null, "Sindicato inserido com sucesso","Inserção", JOptionPane.INFORMATION_MESSAGE);    		
    	}catch(Exception ex){
            JOptionPane.showMessageDialog(null, "ERRO NOMANUSEAMENTO DO FICHEIRO:\n"+ex.getMessage(),"Escrita do Ficheiro", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
    	}
    }
    
    //Leitura do ficheiro de texto e insercão do seu conteudo no array de objecto empresa
    private void loadSindicatos(){ 
        Object rgs[][] = new Sindicato().loadSindicatos();
        sindicatos = (Sindicato[])rgs[0][0];
        nrElem = (int)rgs[0][1];
        
    }
    
    private void loadProvincias(){
        try {
            Provincia[] ps = new Provincia().loadProvincias();
            for(int i=0; i< ps.length; i++){
               cbProv.addItem(ps[i].getCodigo()+" - "+ps[i].getNome());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao manusear a tabela provincia: "+ex.getMessage(), "registo da empresa", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace(); 
        }
    }
    
    private void loadDistritos(int codProv){
        try {
            Distrito[] ds = new Distrito().loadDistritos();
            for(int i=0; i<ds.length; i++){
                if(ds[i].getCodProv() == codProv){
                    cbDist.addItem(ds[i].getCodigo()+" - "+ds[i].getNome());                    
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao manusear a tabela Actividade: "+ex.getMessage(), "registo da empresa", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace(); 
        }
    }   
    
    private void loadActividades(){
        try {
            Actividade[] acts = new Actividade().loadActividades();
            for(int i=0; i<acts.length; i++){
               cbActiv.addItem(acts[i].getCodigo()+" - "+acts[i].getNome());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao manusear a tabela Actividade: "+ex.getMessage(), "registo da empresa", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace(); 
        }
    }   
    
    private void loadTipoRegistos(){
        try {
            TipoRegisto[] trs = new TipoRegisto().loadTipoRegisto();
            for(int i=0; i<trs.length; i++){
               cbTipoReg.addItem(trs[i].getCodigo()+" - "+trs[i].getDesignacao());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao manusear a tabela TIPOREGISTO: "+ex.getMessage(), "registo da empresa", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace(); 
        }
    }         
    
    private void loadCategorias(int codTipoRegisto){
        try {
            Categoria [] cs = new Categoria().loadCategoria();
            for(int i=0; i<cs.length; i++){
                if(cs[i].getCodTipo() == codTipoRegisto){
                    cbCatReg.addItem(cs[i].getCodigo()+" - "+cs[i].getDesignacao());                    
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao manusear a tabela CATEGORIA: "+ex.getMessage(), "registo da empresa", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace(); 
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadSindicato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadSindicato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadSindicato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadSindicato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmCadSindicato dialog = new FrmCadSindicato(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddEmp;
    private javax.swing.JButton btBuscaActa;
    private javax.swing.JButton btBuscaEmp;
    private javax.swing.JButton btBuscaEstatuto;
    private javax.swing.JButton btBuscaLista;
    private javax.swing.JButton btBuscaOutros;
    private javax.swing.JButton btBuscaOutros1;
    private javax.swing.JButton btGravar;
    private javax.swing.JComboBox<String> cbActiv;
    private javax.swing.JComboBox<String> cbCatReg;
    private javax.swing.JComboBox<String> cbDist;
    private javax.swing.JComboBox<String> cbProv;
    private javax.swing.JComboBox<String> cbTipoReg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JFileChooser jfcActa;
    private javax.swing.JFileChooser jfcCertidao;
    private javax.swing.JFileChooser jfcConvocatoria;
    private javax.swing.JFileChooser jfcEstatuto;
    private javax.swing.JFileChooser jfcLista;
    private javax.swing.JTextField txtActaFile;
    private javax.swing.JTextField txtContacto;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextArea txtDesigna;
    private javax.swing.JTextArea txtEndereco;
    private javax.swing.JTextField txtEstatutoFile;
    private javax.swing.JTextField txtFileCertidao;
    private javax.swing.JTextField txtFileConvocatoria;
    private javax.swing.JTextField txtInss;
    private javax.swing.JTextField txtListaFile;
    private javax.swing.JTextField txtNomeEmp;
    private javax.swing.JTextField txtRepresenta;
    private javax.swing.JTextField txtSigla;
    // End of variables declaration//GEN-END:variables
}
