/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewer;

/**
 *
 * @author User
 */
import controler.Actividade;
import controler.Distrito;
import controler.Provincia;
import controler.Empresa;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class FrmCadEmpresa extends javax.swing.JDialog {

    /* Array para receber os dados do ficheiro de texto e manuseamento de dados
       no programa java */
    private Empresa empresas[] = new Empresa[10];
    private int nrElem = 0;
    
    public FrmCadEmpresa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadProvincias();
        loadActividades();
        loadEmpresas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtInss = new javax.swing.JTextField();
        txtNuit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbProv = new javax.swing.JComboBox<>();
        cbDist = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbActiv = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEnde = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTO DA EMPRESA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("NUM. DE INSS *");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("NUM. DE NUIT *");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("NOME DA EMPRESA *");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("PROVINCIA *");

        cbProv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------- Selecciona Provincia -----------" }));
        cbProv.setMaximumSize(new java.awt.Dimension(300, 32767));
        cbProv.setMinimumSize(new java.awt.Dimension(300, 19));
        cbProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProvActionPerformed(evt);
            }
        });

        cbDist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------- Selecciona Distrito -----------" }));
        cbDist.setPreferredSize(new java.awt.Dimension(300, 20));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("DISTRITO *");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("ENDERECO *");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("ACTIVIDADE *");

        cbActiv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------- Selecciona Actividade -----------" }));
        cbActiv.setMinimumSize(new java.awt.Dimension(300, 19));
        cbActiv.setPreferredSize(new java.awt.Dimension(300, 20));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtEnde.setColumns(20);
        txtEnde.setLineWrap(true);
        txtEnde.setRows(2);
        jScrollPane1.setViewportView(txtEnde);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("OBSERVAÇÕES");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtObs.setColumns(20);
        txtObs.setLineWrap(true);
        txtObs.setRows(2);
        jScrollPane2.setViewportView(txtObs);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("TELEFONE *");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbActiv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(cbProv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(cbDist, 0, 399, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNuit)
                                    .addComponent(txtInss)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNome))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTel)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtInss))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNuit)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbProv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbDist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbActiv, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OPERAÇÕES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        btSave.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        btSave.setText("GRAVAR");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProvActionPerformed
        cbDist.removeAllItems();
        cbDist.addItem("--------------- SELECCIONA DISTRITO ---------------");
        if(cbProv.getSelectedIndex() > 0){
            int codProv = Integer.parseInt(cbProv.getSelectedItem().toString().split(" - ")[0]);
            loadDistritos(codProv);
        }
    }//GEN-LAST:event_cbProvActionPerformed

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        String valido = validacao();
        if(valido.isEmpty()){
            int inss = Integer.parseInt(txtInss.getText());
            int nuit = Integer.parseInt(txtNuit.getText());
            String nome = txtNome.getText();
            String dists[] = ((String)cbDist.getSelectedItem()).split(" - ");
            int codDist = Integer.parseInt(dists[0]) ;
            String endereco = txtEnde.getText();
            String activs[] = cbActiv.getSelectedItem().toString().split(" - ");
            int actividade = Integer.parseInt(activs[0]);
            String telefone = txtTel.getText();
            int estado = 1;
            Date dataDesp = null;
            String observacoes = null;
            if(!txtObs.getText().isEmpty()){
                observacoes = txtObs.getText();
            }
            Empresa emp =new Empresa(inss, nuit, nome, codDist, endereco, actividade, telefone, estado, dataDesp, observacoes);
            if(search(inss) == -1){
                addEmpresa(emp);
            }else{
               JOptionPane.showMessageDialog(null, "Já existe empresa com este Número do INSS", "registo da empresa", JOptionPane.ERROR_MESSAGE); 
            }
        }else{
           JOptionPane.showMessageDialog(null, valido, "registo da empresa", JOptionPane.ERROR_MESSAGE); 
        }
     
    }//GEN-LAST:event_btSaveActionPerformed

    
    private void incrementaArry(){
        //verifica se o array está cheio, caso sim duplica a capacidade
        if(nrElem >= empresas.length){
            Empresa aux[]= empresas;
            empresas = new Empresa[aux.length * 2];
            for(int i = 0; i<aux.length; i++){
                empresas[i] = aux[i];
            }
        }
    }

    /* procura se existe uma Empresa com Número do INSS igual ao valor no parametro 
       Existendo retorna a posição em foi inserida a tal Empresa
    */
    private int search(int inssNovaEmp){
    	int index=-1;
    	for(int i=0; i<nrElem; i++){
            if(empresas[i].getNumInss() == inssNovaEmp){
                index=i;
                break;
            }
    	}    
    	return index;
    }
    
    // metodo que insere uma empresa no array de objecto Empresa
    public  void addEmpresa(Empresa novaEmp){
        incrementaArry();
        // insere mais uma empresa no array
        empresas[nrElem] = novaEmp; 
        nrElem++;  
        // actualiza o ficheiro dos estudantes
        updateTextFile();
    }
    
    // Grava todos as empresas do array no ficheiro de texto
    private void updateTextFile(){
    	try{
            FileWriter fileText = new FileWriter(new File("C:\\MyFiles\\GestaoSindicato\\EMPRESA.txt"));
            BufferedWriter writeText = new BufferedWriter(fileText);
            for(int i=0; i< nrElem ; i++){
                writeText.write(empresas[i].toString());
                writeText.newLine();
            }
            writeText.close();
            JOptionPane.showMessageDialog(null, "Estudante inserido com sucesso","Inserção", JOptionPane.INFORMATION_MESSAGE);    		
    	}catch(Exception ex){
            JOptionPane.showMessageDialog(null, "ERRO NOMANUSEAMENTO DO FICHEIRO:\n"+ex.getMessage(),"Escrita do Ficheiro", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
    	}
    }
    
    //Leitura do ficheiro de texto e insercão do seu conteudo no array de objecto empresa
    public void loadEmpresas(){  
        Object regs[][] = new Empresa().loadEmpresas();
        empresas = (Empresa[])regs[0][0];
        nrElem = (int)regs[0][1];
    }
    
    
    private void loadProvincias(){
        try {
            Provincia[] ps = new Provincia().loadProvincias();
            for(int i=0; i< ps.length; i++){
               cbProv.addItem(ps[i].getCodigo()+" - "+ps[i].getNome());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao manusear a tabela provincia: "+ex.getMessage(), "registo da empresa", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace(); 
        }
    }
    
    private void loadDistritos(int codProv){
        try {
            Distrito[] ds = new Distrito().loadDistritos();
            for(int i=0; i<ds.length; i++){
                if(ds[i].getCodProv() == codProv){
                    cbDist.addItem(ds[i].getCodigo()+" - "+ds[i].getNome());                    
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao manusear a tabela Actividade: "+ex.getMessage(), "registo da empresa", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace(); 
        }
    }   
    
    private void loadActividades(){
        try {
            Actividade[] acts = new Actividade().loadActividades();
            for(int i=0; i<acts.length; i++){
               cbActiv.addItem(acts[i].getCodigo()+" - "+acts[i].getNome());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao manusear a tabela Actividade: "+ex.getMessage(), "registo da empresa", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace(); 
        }
    }  
            
    private String validacao(){
        String erro="";
        if(txtInss.getText().isEmpty()){
            erro +="O campo INSS deve ser preenchido\n";
        }
        if(txtNuit.getText().isEmpty()){
            erro +="O campo NUIT deve ser preenchido\n";
        }
        if(txtNome.getText().isEmpty()){
            erro +="O campo Nome deve ser preenchido\n";
        }
        if(txtEnde.getText().isEmpty()){
            erro +="O campo Endereco deve ser preenchido\n";
        }
        if(txtTel.getText().isEmpty()){
            erro +="O campo Telefone deve ser preenchido\n";
        }
        if(cbProv.getSelectedIndex() < 1){
            erro +="O campo Provincia deve ser seleccionado\n";
        }
        if(cbDist.getSelectedIndex() < 1){
            erro +="O campo Distrito deve ser seleccionado\n";
        }
        if(cbActiv.getSelectedIndex() < 1){
            erro +="O campo Actividade deve ser seleccionado\n";
        }    
        return erro;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmCadEmpresa dialog = new FrmCadEmpresa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSave;
    private javax.swing.JComboBox<String> cbActiv;
    private javax.swing.JComboBox<String> cbDist;
    private javax.swing.JComboBox<String> cbProv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtEnde;
    private javax.swing.JTextField txtInss;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNuit;
    private javax.swing.JTextArea txtObs;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
