/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewer;

import controler.*;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FrmDetalhesSindicato extends javax.swing.JDialog {

    Sindicato sind = new Sindicato();
    /**
     * Creates new form FrmDetalhesEmpresa
     */
    public FrmDetalhesSindicato(java.awt.Frame parent, boolean modal, Sindicato sind) {
        super(parent, modal);
        initComponents();
        this.sind = sind;
        preencheDados();
        tomadaDecisao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgDespacho = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtSigla = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtRepresentante = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtProvincia = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtContacto = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtDistrito = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesignacao = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtSector = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtInss = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtFileActa = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtFileEstatuto = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtFilePresencas = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtFileCertidao = new javax.swing.JTextField();
        btOpenEstatuto = new javax.swing.JButton();
        btOpenActa = new javax.swing.JButton();
        btOpenPresencas = new javax.swing.JButton();
        btOpenCertidao = new javax.swing.JButton();
        btOpenEmpresa = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txtFileConvocatoria = new javax.swing.JTextField();
        btOpenConvocatoria = new javax.swing.JButton();
        txtCategoria = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtDataDespacho = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btAprovar = new javax.swing.JButton();
        pnRejeicao = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ckActa = new javax.swing.JCheckBox();
        ckLista = new javax.swing.JCheckBox();
        ckEstatuto = new javax.swing.JCheckBox();
        ckCertidao = new javax.swing.JCheckBox();
        ckConvocatoria = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        rbAprovar = new javax.swing.JRadioButton();
        rbRejeitar = new javax.swing.JRadioButton();
        jLabel35 = new javax.swing.JLabel();
        txtDespacho = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "DETALHES DO SINDICATO/ASSOCIAÇÃO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(51, 0, 255))); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("CODIGO");

        txtCodigo.setEditable(false);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("SIGLA");

        txtSigla.setEditable(false);
        txtSigla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSiglaActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("DESIGNAÇÃO");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("REPRESENTANTE");

        txtRepresentante.setEditable(false);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("PROVINCIA");

        txtProvincia.setEditable(false);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("ENDEREÇO");

        txtEndereco.setEditable(false);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("CONTACTO");

        txtContacto.setEditable(false);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel31.setText("DATA DO REGISTO");

        txtData.setEditable(false);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel34.setText("DISTRITO");

        txtDistrito.setEditable(false);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("ESTADO");

        txtEstado.setEditable(false);

        txtDesignacao.setEditable(false);
        txtDesignacao.setColumns(20);
        txtDesignacao.setLineWrap(true);
        txtDesignacao.setRows(2);
        jScrollPane1.setViewportView(txtDesignacao);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtData, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(txtContacto, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(txtDistrito, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(txtProvincia, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(txtRepresentante, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(txtEstado)
                            .addComponent(jScrollPane1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txtDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("CATEGORIA");

        txtTipo.setEditable(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("DATA DO DESPACHO");

        txtSector.setEditable(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("INSS EMPRESA");

        txtInss.setEditable(false);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("FICHEIRO ACTA");

        txtFileActa.setEditable(false);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("FICHEIRO ESTATUTO");

        txtFileEstatuto.setEditable(false);
        txtFileEstatuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFileEstatutoActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("FICHEIRO PRESENÇAS");

        txtFilePresencas.setEditable(false);
        txtFilePresencas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFilePresencasMouseClicked(evt);
            }
        });
        txtFilePresencas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilePresencasActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("CERTIDÃO");

        txtFileCertidao.setEditable(false);
        txtFileCertidao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFileCertidaoActionPerformed(evt);
            }
        });

        btOpenEstatuto.setBackground(new java.awt.Color(204, 255, 204));
        btOpenEstatuto.setForeground(new java.awt.Color(255, 0, 0));
        btOpenEstatuto.setText("Abrir Ficheiro");
        btOpenEstatuto.setEnabled(false);
        btOpenEstatuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOpenEstatutoActionPerformed(evt);
            }
        });

        btOpenActa.setBackground(new java.awt.Color(204, 255, 204));
        btOpenActa.setForeground(new java.awt.Color(255, 0, 0));
        btOpenActa.setText("Abrir Ficheiro");
        btOpenActa.setEnabled(false);
        btOpenActa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOpenActaActionPerformed(evt);
            }
        });

        btOpenPresencas.setBackground(new java.awt.Color(204, 255, 204));
        btOpenPresencas.setForeground(new java.awt.Color(255, 0, 0));
        btOpenPresencas.setText("Abrir Ficheiro");
        btOpenPresencas.setEnabled(false);
        btOpenPresencas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOpenPresencasActionPerformed(evt);
            }
        });

        btOpenCertidao.setBackground(new java.awt.Color(204, 255, 204));
        btOpenCertidao.setForeground(new java.awt.Color(255, 0, 0));
        btOpenCertidao.setText("Abrir Ficheiro");
        btOpenCertidao.setEnabled(false);
        btOpenCertidao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOpenCertidaoActionPerformed(evt);
            }
        });

        btOpenEmpresa.setBackground(new java.awt.Color(204, 255, 204));
        btOpenEmpresa.setForeground(new java.awt.Color(255, 0, 0));
        btOpenEmpresa.setText("Buscar Empresa");
        btOpenEmpresa.setEnabled(false);
        btOpenEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOpenEmpresaActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("CONVOCATÓRIA");

        txtFileConvocatoria.setEditable(false);
        txtFileConvocatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFileConvocatoriaActionPerformed(evt);
            }
        });

        btOpenConvocatoria.setBackground(new java.awt.Color(204, 255, 204));
        btOpenConvocatoria.setForeground(new java.awt.Color(255, 0, 0));
        btOpenConvocatoria.setText("Abrir Ficheiro");
        btOpenConvocatoria.setEnabled(false);
        btOpenConvocatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOpenConvocatoriaActionPerformed(evt);
            }
        });

        txtCategoria.setEditable(false);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel32.setText("RAMO DE ACTIVIDADE");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("TIPO");

        txtDataDespacho.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFilePresencas, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFileCertidao, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFileEstatuto, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFileConvocatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtSector, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                                        .addComponent(txtTipo, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtDataDespacho, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtFileActa, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtInss, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btOpenPresencas, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btOpenCertidao, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btOpenEstatuto, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btOpenEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btOpenActa, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btOpenConvocatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txtSector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtDataDespacho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtInss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btOpenEmpresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtFileActa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btOpenActa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtFileEstatuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btOpenEstatuto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtFilePresencas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btOpenPresencas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFileCertidao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btOpenCertidao)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFileConvocatoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btOpenConvocatoria)
                    .addComponent(jLabel21))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        btAprovar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btAprovar.setText("EXECUTAR O DESPACHO");
        btAprovar.setEnabled(false);
        btAprovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAprovarActionPerformed(evt);
            }
        });

        pnRejeicao.setBackground(new java.awt.Color(204, 255, 204));
        pnRejeicao.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DOCUMENTOS COM IRREGULARIDADES");

        ckActa.setText("•    Acta da Assembleia Constituinte");
        ckActa.setEnabled(false);
        ckActa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckActaActionPerformed(evt);
            }
        });

        ckLista.setText("•    Lista Nominal dos presentes na Assembleia constituinte");
        ckLista.setEnabled(false);
        ckLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckListaActionPerformed(evt);
            }
        });

        ckEstatuto.setText("•    Estatuto da associação");
        ckEstatuto.setEnabled(false);
        ckEstatuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckEstatutoActionPerformed(evt);
            }
        });

        ckCertidao.setText("•    Certidão negativa da denominação da associação");
        ckCertidao.setEnabled(false);
        ckCertidao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckCertidaoActionPerformed(evt);
            }
        });

        ckConvocatoria.setText("•    Documento comprovativo da publicação da convocatória da assembleia Constituinte");
        ckConvocatoria.setEnabled(false);
        ckConvocatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckConvocatoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnRejeicaoLayout = new javax.swing.GroupLayout(pnRejeicao);
        pnRejeicao.setLayout(pnRejeicaoLayout);
        pnRejeicaoLayout.setHorizontalGroup(
            pnRejeicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRejeicaoLayout.createSequentialGroup()
                .addGroup(pnRejeicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnRejeicaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnRejeicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckCertidao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ckConvocatoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnRejeicaoLayout.createSequentialGroup()
                                .addComponent(ckEstatuto, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 56, Short.MAX_VALUE))
                            .addComponent(ckLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ckActa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnRejeicaoLayout.setVerticalGroup(
            pnRejeicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRejeicaoLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addComponent(ckActa)
                .addGap(2, 2, 2)
                .addComponent(ckLista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckEstatuto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckCertidao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckConvocatoria)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));

        bgDespacho.add(rbAprovar);
        rbAprovar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rbAprovar.setForeground(new java.awt.Color(0, 0, 204));
        rbAprovar.setSelected(true);
        rbAprovar.setText("APROVAR");
        rbAprovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAprovarActionPerformed(evt);
            }
        });

        bgDespacho.add(rbRejeitar);
        rbRejeitar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rbRejeitar.setForeground(new java.awt.Color(0, 0, 204));
        rbRejeitar.setText("REJEITAR");
        rbRejeitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRejeitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rbRejeitar, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(rbAprovar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(rbAprovar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbRejeitar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnRejeicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btAprovar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(90, 90, 90))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnRejeicao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btAprovar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel35.setText("DESPACHO");

        txtDespacho.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDespacho, javax.swing.GroupLayout.PREFERRED_SIZE, 1108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txtDespacho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSiglaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSiglaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSiglaActionPerformed

    private void txtFileEstatutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFileEstatutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFileEstatutoActionPerformed

    private void txtFilePresencasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFilePresencasMouseClicked

    }//GEN-LAST:event_txtFilePresencasMouseClicked

    private void txtFilePresencasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilePresencasActionPerformed

    }//GEN-LAST:event_txtFilePresencasActionPerformed

    private void txtFileCertidaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFileCertidaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFileCertidaoActionPerformed

    private void btOpenEstatutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOpenEstatutoActionPerformed
        try{
            String value= txtFileEstatuto.getText().toString(); 
            Runtime.getRuntime().exec("rundll32 SHELL32.DLL,ShellExec_RunDLL "+value, null, null);
        }catch(Exception ex){
            JOptionPane.showInternalMessageDialog(null, "Erro no acesso ao ficheiro do Estatuto \n "+ex.getMessage(), "select", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btOpenEstatutoActionPerformed

    private void btOpenActaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOpenActaActionPerformed
        try{
            String value= txtFileActa.getText().toString(); 
            Runtime.getRuntime().exec("rundll32 SHELL32.DLL,ShellExec_RunDLL "+value, null, null);
        }catch(Exception ex){
            JOptionPane.showInternalMessageDialog(null, "Erro no acesso ao ficheiro da Acta \n "+ex.getMessage(), "select", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btOpenActaActionPerformed

    private void btOpenPresencasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOpenPresencasActionPerformed
        try{
            String value= txtFilePresencas.getText().toString(); 
            Runtime.getRuntime().exec("rundll32 SHELL32.DLL,ShellExec_RunDLL "+value, null, null);
        }catch(Exception ex){
            JOptionPane.showInternalMessageDialog(null, "Erro no acesso ao ficheiro da Lista de Presenças \n "+ex.getMessage(), "select", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btOpenPresencasActionPerformed

    private void btOpenCertidaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOpenCertidaoActionPerformed
        try{
            String value= txtFileCertidao.getText().toString(); 
            Runtime.getRuntime().exec("rundll32 SHELL32.DLL,ShellExec_RunDLL "+value, null, null);
        }catch(Exception ex){
            JOptionPane.showInternalMessageDialog(null, "Erro no acesso ao ficheiro da Certidão Negativa da Denominação \n "+ex.getMessage(), "select", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btOpenCertidaoActionPerformed

    private void btOpenEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOpenEmpresaActionPerformed
        try {
            int numInss = Integer.parseInt(txtInss.getText());
                Empresa emp = new Empresa().findEmpresa(numInss);
                FrmDetalhesEmpresa view = new FrmDetalhesEmpresa(null, true, emp);
                view.setLocationRelativeTo(null);
                view.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERRO:", "registo da empresa", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_btOpenEmpresaActionPerformed

    private void txtFileConvocatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFileConvocatoriaActionPerformed
        
    }//GEN-LAST:event_txtFileConvocatoriaActionPerformed

    private void btOpenConvocatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOpenConvocatoriaActionPerformed
        try{
            String value= txtFileConvocatoria.getText().toString(); 
            Runtime.getRuntime().exec("rundll32 SHELL32.DLL,ShellExec_RunDLL "+value, null, null);
        }catch(Exception ex){
            JOptionPane.showInternalMessageDialog(null, "Erro no acesso ao ficheiro da Convocatória publicada \n "+ex.getMessage(), "select", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btOpenConvocatoriaActionPerformed

    private void btAprovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAprovarActionPerformed
        if(!txtCodigo.getText().isEmpty()){
            int codigo = Integer.parseInt(txtCodigo.getText());
            String despacho ;             
            if(rbAprovar.isSelected()){
                despacho = "Processo devidamente instruido, Registo Aprovado"; 
                aprovaRegisto(codigo, despacho);
            }else{
                String motivos ="";
                if(ckConvocatoria.isSelected()){
                    motivos += ckConvocatoria.getText() +"; ";
                }
                if(ckLista.isSelected()){
                    motivos += ckLista.getText() +"; ";
                }
                if(ckActa.isSelected()){
                    motivos += ckActa.getText() +"; ";
                }
                if(ckActa.isSelected()){
                    motivos += ckActa.getText() +"; ";
                }
                if(ckCertidao.isSelected()){
                    motivos += ckCertidao.getText() +"; ";
                }
                despacho = "Registo Rejeitado deve regularizar os documentos : "; 
                rejeitarRegisto(codigo, despacho + motivos);
            }
        }
    }//GEN-LAST:event_btAprovarActionPerformed

    private void ckActaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckActaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckActaActionPerformed

    private void ckListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckListaActionPerformed

    private void ckEstatutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckEstatutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckEstatutoActionPerformed

    private void ckCertidaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckCertidaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckCertidaoActionPerformed

    private void ckConvocatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckConvocatoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckConvocatoriaActionPerformed

    private void rbAprovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAprovarActionPerformed
        ckActa.setSelected(false);
        ckLista.setSelected(false);
        ckEstatuto.setSelected(false);
        ckCertidao.setSelected(false);
        ckConvocatoria.setSelected(false);
        ckActa.setEnabled(false);
        ckLista.setEnabled(false);
        ckEstatuto.setEnabled(false);
        ckCertidao.setEnabled(false);
        ckConvocatoria.setEnabled(false);
    }//GEN-LAST:event_rbAprovarActionPerformed

    private void rbRejeitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRejeitarActionPerformed
        ckActa.setEnabled(true);
        ckLista.setEnabled(true);
        ckEstatuto.setEnabled(true);
        ckCertidao.setEnabled(true);
        ckConvocatoria.setEnabled(true);
    }//GEN-LAST:event_rbRejeitarActionPerformed

    private void preencheDados(){
        txtCodigo.setText(String.valueOf(sind.getCodigo()));
        txtSigla.setText(sind.getSigla());
        txtDesignacao.setText(sind.getDesignacao());
        txtRepresentante.setText(sind.getRepresentante());
        Distrito dist = new Distrito().findDistrito(sind.getCodDist());
        Provincia prov = new Provincia().findProvincia(dist.getCodProv());
        txtProvincia.setText(prov.getNome());
        txtDistrito.setText(dist.getNome());
        txtEndereco.setText(sind.getEndereco());
        txtContacto.setText(sind.getContacto());
        txtData.setText(String.valueOf(sind.getData()));
        Categoria categ = new Categoria().findCategoria(sind.getCategoria());
        txtCategoria.setText(categ.getDesignacao());
        EstadoSindicato estado = new EstadoSindicato().findEstado(sind.getEstado());
        txtEstado.setText(estado.getEstado());
        TipoRegisto tipo = new TipoRegisto().findEstado(categ.getCodTipo());
        txtTipo.setText(tipo.getDesignacao());
        if(sind.getCodActiv() != 0){
            Actividade activ = new Actividade().findActividade(sind.getCodActiv());
            txtSector.setText(activ.getNome());
        }        
        txtDataDespacho.setText(String.valueOf(sind.getDataDespacho()));
        txtDespacho.setText(sind.getDespacho());
        if(sind.getNumInss() != 0){
            txtInss.setText(String.valueOf(sind.getNumInss()));
            btOpenEmpresa.setEnabled(true);
        }
        if(sind.getFileActa().length()>5){
            txtFileActa.setText(sind.getFileActa());
            btOpenActa.setEnabled(true);
        }
        if(sind.getFileEstatuto().length()>5){
            txtFileEstatuto.setText(sind.getFileEstatuto());
            btOpenEstatuto.setEnabled(true);
        }
        if(sind.getFileLista().length()>5){
            txtFilePresencas.setText(sind.getFileLista());
            btOpenPresencas.setEnabled(true);
        }
        if(sind.getFileCertidao().length()>5){
            txtFileCertidao.setText(sind.getFileCertidao());
            btOpenCertidao.setEnabled(true);
        }
        if(sind.getFileConvocatoria().length()>5){
            txtFileConvocatoria.setText(sind.getFileConvocatoria());
            btOpenConvocatoria.setEnabled(true);
        }
    }
    
    private void tomadaDecisao(){
        if(txtEstado.getText().equalsIgnoreCase("Registado") ){
            btAprovar.setEnabled(true);
        }else{
            btAprovar.setEnabled(false);
        }
    }
    
    private void aprovaRegisto(int codigo, String despacho){
        try{           
             String data = new SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date());
             System.out.println(data);
             Object regs[][] = new Sindicato().loadSindicatos();
             Sindicato sindicatos[] = (Sindicato[])regs[0][0];
             int nrElem = (int)regs[0][1];
             int index = search(sindicatos, nrElem, codigo);
             if(index != -1){
                 sindicatos[index].setEstado(2);
                 sindicatos[index].setDataDespacho(Date.valueOf(data));
                 sindicatos[index].setDespacho(despacho);
             }
             updateTextFile(sindicatos, nrElem);
            JOptionPane.showInternalMessageDialog(null, "Sindicato Aprovado com sucesso", "despacho do registo", JOptionPane.INFORMATION_MESSAGE);
             txtEstado.setText("APROVADO");
             txtDataDespacho.setText(data);
             txtDespacho.setText(despacho);
             btAprovar.setEnabled(false);               
        }catch(Exception ex){
            JOptionPane.showInternalMessageDialog(null, "Erro na Aprovação do Registo do Sindicato \n "+ex.getMessage(), "select", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
    
    private void rejeitarRegisto(int codigo, String despacho){
        try{           
             String data = new SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date());
             System.out.println(data);
             Object regs[][] = new Sindicato().loadSindicatos();
             Sindicato sindicatos[] = (Sindicato[])regs[0][0];
             int nrElem = (int)regs[0][1];
             int index = search(sindicatos, nrElem, codigo);
             if(index != -1){
                 sindicatos[index].setEstado(3);
                 sindicatos[index].setDataDespacho(Date.valueOf(data));
                 sindicatos[index].setDespacho(despacho);
             }
             updateTextFile(sindicatos, nrElem);
            JOptionPane.showInternalMessageDialog(null, "Sindicato Rejeitado", "despacho do registo", JOptionPane.INFORMATION_MESSAGE);
             txtEstado.setText("REJEITADO");
             txtDataDespacho.setText(data);
             txtDespacho.setText(despacho);
             btAprovar.setEnabled(false);               
        }catch(Exception ex){
            JOptionPane.showInternalMessageDialog(null, "Erro na Aprovação do Registo do Sindicato \n "+ex.getMessage(), "select", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
    
    public int search(Sindicato sinds[], int nrElem, int codigo){
        int index =0;
        for(int i =0; i<nrElem; i++){
            if(sinds[i].getCodigo() == codigo){
                index = i;
                break;
            }
        }
        return index;
    }
    
    // Grava todos as empresas do array no ficheiro de texto
    private void updateTextFile(Sindicato[] sinds, int nrElem){
    	try{
            FileWriter fileText = new FileWriter(new File("C:\\MyFiles\\GestaoSindicato\\SINDICATO.txt"));
            BufferedWriter writeText = new BufferedWriter(fileText);
            for(int i=0; i< nrElem ; i++){
                writeText.write(sinds[i].toString());
                writeText.newLine();
            }
            writeText.close();
            JOptionPane.showMessageDialog(null, "Sindicato inserido com sucesso","Inserção", JOptionPane.INFORMATION_MESSAGE);    		
    	}catch(Exception ex){
            JOptionPane.showMessageDialog(null, "ERRO NOMANUSEAMENTO DO FICHEIRO:\n"+ex.getMessage(),"Escrita do Ficheiro", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
    	}
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDetalhesSindicato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDetalhesSindicato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDetalhesSindicato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDetalhesSindicato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmDetalhesSindicato dialog = new FrmDetalhesSindicato(new javax.swing.JFrame(), true, new Sindicato());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgDespacho;
    private javax.swing.JButton btAprovar;
    private javax.swing.JButton btOpenActa;
    private javax.swing.JButton btOpenCertidao;
    private javax.swing.JButton btOpenConvocatoria;
    private javax.swing.JButton btOpenEmpresa;
    private javax.swing.JButton btOpenEstatuto;
    private javax.swing.JButton btOpenPresencas;
    private javax.swing.JCheckBox ckActa;
    private javax.swing.JCheckBox ckCertidao;
    private javax.swing.JCheckBox ckConvocatoria;
    private javax.swing.JCheckBox ckEstatuto;
    private javax.swing.JCheckBox ckLista;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnRejeicao;
    private javax.swing.JRadioButton rbAprovar;
    private javax.swing.JRadioButton rbRejeitar;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtContacto;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtDataDespacho;
    private javax.swing.JTextArea txtDesignacao;
    private javax.swing.JTextField txtDespacho;
    private javax.swing.JTextField txtDistrito;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFileActa;
    private javax.swing.JTextField txtFileCertidao;
    private javax.swing.JTextField txtFileConvocatoria;
    private javax.swing.JTextField txtFileEstatuto;
    private javax.swing.JTextField txtFilePresencas;
    private javax.swing.JTextField txtInss;
    private javax.swing.JTextField txtProvincia;
    private javax.swing.JTextField txtRepresentante;
    private javax.swing.JTextField txtSector;
    private javax.swing.JTextField txtSigla;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
