/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewer;

import controler.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class FrmListUsuario extends javax.swing.JDialog {
    DefaultTableModel model;
    /* Array para receber os dados do ficheiro de texto e manuseamento de dados
       no programa java */
    private Usuario users[] = new Usuario[10];
    private int nrElem = 0;
    
    public FrmListUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model = (DefaultTableModel)tbDados.getModel();
        loadUsuarios();
        preencheTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LISTA DE USUARIOS REGISTADAS NO SISTEMA DE GESTÃO DE SINDICATOS");

        tbDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME USUARIO", "NOME COMPLETO", "TELEFONE", "EMAIL", "TIPOUSER"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDados);
        if (tbDados.getColumnModel().getColumnCount() > 0) {
            tbDados.getColumnModel().getColumn(0).setMinWidth(40);
            tbDados.getColumnModel().getColumn(0).setPreferredWidth(60);
            tbDados.getColumnModel().getColumn(0).setMaxWidth(100);
            tbDados.getColumnModel().getColumn(1).setMinWidth(50);
            tbDados.getColumnModel().getColumn(1).setPreferredWidth(100);
            tbDados.getColumnModel().getColumn(1).setMaxWidth(150);
            tbDados.getColumnModel().getColumn(2).setMinWidth(100);
            tbDados.getColumnModel().getColumn(2).setPreferredWidth(150);
            tbDados.getColumnModel().getColumn(2).setMaxWidth(400);
            tbDados.getColumnModel().getColumn(3).setMinWidth(100);
            tbDados.getColumnModel().getColumn(3).setPreferredWidth(75);
            tbDados.getColumnModel().getColumn(3).setMaxWidth(150);
            tbDados.getColumnModel().getColumn(4).setMinWidth(100);
            tbDados.getColumnModel().getColumn(4).setPreferredWidth(200);
            tbDados.getColumnModel().getColumn(4).setMaxWidth(400);
            tbDados.getColumnModel().getColumn(5).setMinWidth(75);
            tbDados.getColumnModel().getColumn(5).setPreferredWidth(100);
            tbDados.getColumnModel().getColumn(5).setMaxWidth(150);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDadosMouseClicked
        
    }//GEN-LAST:event_tbDadosMouseClicked

    private void incrementaArry(){
        //verifica se o array está cheio, caso sim duplica a capacidade
        if(nrElem >= users.length){
            Usuario aux[]= users;
            users = new Usuario[aux.length * 2];
            for(int i = 0; i<aux.length; i++){
                users[i] = aux[i];
            }
        }
    }
    
    //Leitura do ficheiro de texto e insercão do seu conteudo no array de objecto empresa
    public void loadUsuarios(){ 
        Object regs[][] = new Usuario().loadUsuarios();
        users = (Usuario[])regs[0][0];
        nrElem = (int)regs[0][1];
    }
    
    private void preencheTabela(){
        for(int i=0; i<nrElem; i++){
            System.out.println(users[i].toString());
            model.addRow(new Object[]{users[i].getId(), users[i].getUsername(), users[i].getNomecompleto(),users[i].getTelefone(), users[i].getEmail(), users[i].getTipouser()});
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmListUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmListUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmListUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmListUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmListUsuario dialog = new FrmListUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDados;
    // End of variables declaration//GEN-END:variables
}
