/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewer;

/**
 *
 * @author User
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnCadastros = new javax.swing.JMenu();
        mnCadEmpresa = new javax.swing.JMenuItem();
        mnCadSindicato = new javax.swing.JMenuItem();
        mnCadUsuario = new javax.swing.JMenuItem();
        mnListagens = new javax.swing.JMenu();
        mnListSindicatos = new javax.swing.JMenu();
        mnListSindicatosTodos = new javax.swing.JMenuItem();
        mnListSindicatosPendentes = new javax.swing.JMenuItem();
        mnListSindicatosAprovados = new javax.swing.JMenuItem();
        mnListSindicatosRejeitados = new javax.swing.JMenuItem();
        mnListEmpresas = new javax.swing.JMenu();
        mnListEmpresasTodas = new javax.swing.JMenuItem();
        mnListEmpresasPendentes = new javax.swing.JMenuItem();
        mnListEmpresasAprovadas = new javax.swing.JMenuItem();
        mnListEmpresaRejeitadas = new javax.swing.JMenuItem();
        mnLisUsuarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        mnCadastros.setText("Cadastros");

        mnCadEmpresa.setText("Empresa");
        mnCadEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadEmpresaActionPerformed(evt);
            }
        });
        mnCadastros.add(mnCadEmpresa);

        mnCadSindicato.setText("Sindicato");
        mnCadSindicato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadSindicatoActionPerformed(evt);
            }
        });
        mnCadastros.add(mnCadSindicato);

        mnCadUsuario.setText("Usuario");
        mnCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadUsuarioActionPerformed(evt);
            }
        });
        mnCadastros.add(mnCadUsuario);

        jMenuBar1.add(mnCadastros);

        mnListagens.setText("Listagens");

        mnListSindicatos.setText("Sindicatos");

        mnListSindicatosTodos.setText("Todos Sindicatos");
        mnListSindicatosTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnListSindicatosTodosActionPerformed(evt);
            }
        });
        mnListSindicatos.add(mnListSindicatosTodos);

        mnListSindicatosPendentes.setText("Pedidos de Registos de Sindicatos");
        mnListSindicatosPendentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnListSindicatosPendentesActionPerformed(evt);
            }
        });
        mnListSindicatos.add(mnListSindicatosPendentes);

        mnListSindicatosAprovados.setText("Sindicatos Aprovados");
        mnListSindicatosAprovados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnListSindicatosAprovadosActionPerformed(evt);
            }
        });
        mnListSindicatos.add(mnListSindicatosAprovados);

        mnListSindicatosRejeitados.setText("Sindicatos Rejeitados");
        mnListSindicatosRejeitados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnListSindicatosRejeitadosActionPerformed(evt);
            }
        });
        mnListSindicatos.add(mnListSindicatosRejeitados);

        mnListagens.add(mnListSindicatos);

        mnListEmpresas.setText("Empresas");

        mnListEmpresasTodas.setText("Todas Empresas");
        mnListEmpresasTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnListEmpresasTodasActionPerformed(evt);
            }
        });
        mnListEmpresas.add(mnListEmpresasTodas);

        mnListEmpresasPendentes.setText("Peidos de Registos de Empresas");
        mnListEmpresasPendentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnListEmpresasPendentesActionPerformed(evt);
            }
        });
        mnListEmpresas.add(mnListEmpresasPendentes);

        mnListEmpresasAprovadas.setText("Empresas Aprovadas");
        mnListEmpresasAprovadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnListEmpresasAprovadasActionPerformed(evt);
            }
        });
        mnListEmpresas.add(mnListEmpresasAprovadas);

        mnListEmpresaRejeitadas.setText("Registos de Empresas Rejeitadas");
        mnListEmpresaRejeitadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnListEmpresaRejeitadasActionPerformed(evt);
            }
        });
        mnListEmpresas.add(mnListEmpresaRejeitadas);

        mnListagens.add(mnListEmpresas);

        mnLisUsuarios.setText("Todos Usuários");
        mnLisUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLisUsuariosActionPerformed(evt);
            }
        });
        mnListagens.add(mnLisUsuarios);

        jMenuBar1.add(mnListagens);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadUsuarioActionPerformed
        FrmCadUser view = new FrmCadUser(null, true);
        view.setLocationRelativeTo(null);
        view.setVisible(true);
    }//GEN-LAST:event_mnCadUsuarioActionPerformed

    private void mnListEmpresasTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnListEmpresasTodasActionPerformed
        FrmListEmpresaTodas view = new FrmListEmpresaTodas(null, true);
        view.setLocationRelativeTo(null);
        view.setVisible(true);
    }//GEN-LAST:event_mnListEmpresasTodasActionPerformed

    private void mnCadEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadEmpresaActionPerformed
        FrmCadEmpresa view = new FrmCadEmpresa(null, true);
        view.setLocationRelativeTo(null);
        view.setVisible(true);
    }//GEN-LAST:event_mnCadEmpresaActionPerformed

    private void mnCadSindicatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadSindicatoActionPerformed
        FrmCadSindicato view = new FrmCadSindicato(null, true);
        view.setLocationRelativeTo(null);
        view.setVisible(true);
    }//GEN-LAST:event_mnCadSindicatoActionPerformed

    private void mnListSindicatosTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnListSindicatosTodosActionPerformed
        FrmListSindicatoTodos view = new FrmListSindicatoTodos(null, true);
        view.setLocationRelativeTo(null);
        view.setVisible(true);
    }//GEN-LAST:event_mnListSindicatosTodosActionPerformed

    private void mnListEmpresasAprovadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnListEmpresasAprovadasActionPerformed
        FrmListEmpresaFilter view = new FrmListEmpresaFilter(null, true, 2);
        view.setLocationRelativeTo(null);
        view.setVisible(true);
    }//GEN-LAST:event_mnListEmpresasAprovadasActionPerformed

    private void mnListEmpresasPendentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnListEmpresasPendentesActionPerformed
        FrmListEmpresaFilter view = new FrmListEmpresaFilter(null, true, 1);
        view.setLocationRelativeTo(null);
        view.setVisible(true);
    }//GEN-LAST:event_mnListEmpresasPendentesActionPerformed

    private void mnListEmpresaRejeitadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnListEmpresaRejeitadasActionPerformed
        FrmListEmpresaFilter view = new FrmListEmpresaFilter(null, true, 3);
        view.setLocationRelativeTo(null);
        view.setVisible(true);
    }//GEN-LAST:event_mnListEmpresaRejeitadasActionPerformed

    private void mnListSindicatosPendentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnListSindicatosPendentesActionPerformed
        FrmListSindicatoFilter view = new FrmListSindicatoFilter(null, true, 1);
        view.setLocationRelativeTo(null);
        view.setVisible(true);
    }//GEN-LAST:event_mnListSindicatosPendentesActionPerformed

    private void mnListSindicatosAprovadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnListSindicatosAprovadosActionPerformed
        FrmListSindicatoFilter view = new FrmListSindicatoFilter(null, true, 2);
        view.setLocationRelativeTo(null);
        view.setVisible(true);
    }//GEN-LAST:event_mnListSindicatosAprovadosActionPerformed

    private void mnListSindicatosRejeitadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnListSindicatosRejeitadosActionPerformed
        FrmListSindicatoFilter view = new FrmListSindicatoFilter(null, true, 3);
        view.setLocationRelativeTo(null);
        view.setVisible(true);
    }//GEN-LAST:event_mnListSindicatosRejeitadosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnLisUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLisUsuariosActionPerformed
        FrmListUsuario view = new FrmListUsuario(null, true);
        view.setLocationRelativeTo(null);
        view.setVisible(true);
    }//GEN-LAST:event_mnLisUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem mnCadEmpresa;
    private javax.swing.JMenuItem mnCadSindicato;
    private javax.swing.JMenuItem mnCadUsuario;
    private javax.swing.JMenu mnCadastros;
    private javax.swing.JMenuItem mnLisUsuarios;
    private javax.swing.JMenuItem mnListEmpresaRejeitadas;
    private javax.swing.JMenu mnListEmpresas;
    private javax.swing.JMenuItem mnListEmpresasAprovadas;
    private javax.swing.JMenuItem mnListEmpresasPendentes;
    private javax.swing.JMenuItem mnListEmpresasTodas;
    private javax.swing.JMenu mnListSindicatos;
    private javax.swing.JMenuItem mnListSindicatosAprovados;
    private javax.swing.JMenuItem mnListSindicatosPendentes;
    private javax.swing.JMenuItem mnListSindicatosRejeitados;
    private javax.swing.JMenuItem mnListSindicatosTodos;
    private javax.swing.JMenu mnListagens;
    // End of variables declaration//GEN-END:variables
}
